import React,{useEffect,useState} from "react";
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,Alert,Linking} from "react-native";
import {StatusBar} from "expo-status-bar";
import * as ImagePicker from "expo-image-picker";
import {initializeApp} from "firebase/app";
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut} from "firebase/auth";

const firebaseConfig={apiKey:"AIzaSyDbwotWs3YoHuZQDX83iTW8XRegfbuXX9k",authDomain:"app2026chat.firebaseapp.com",projectId:"app2026chat",storageBucket:"app2026chat.firebasestorage.app",messagingSenderId:"467492070561",appId:"1:467492070561:web:0540e5f54e01c0c4027ce0"};
const auth=getAuth(initializeApp(firebaseConfig));
const API=process.env.EXPO_PUBLIC_API_PROXY||"https://YOUR-NETLIFY-SITE.netlify.app/.netlify/functions/api";
async function callApi(path,body){const r=await fetch(API+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Erro na API");return d;}

function Logo(){return <View style={s.logo}><View style={s.mark}><Text style={s.markText}>M</Text></View><View><Text style={s.logoName}>MAN CHECKOUT</Text><Text style={s.logoSub}>LINK DE PAGAMENTO</Text></View></View>}
function Btn({title,onPress,secondary=false}){return <Pressable onPress={onPress} style={[s.btn,secondary&&s.btn2]}><Text style={s.btnText}>{title}</Text></Pressable>}
function Input({label,...p}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput {...p} placeholderTextColor="#6e7890" style={s.input}/></View>}

function Auth(){const [mode,setMode]=useState("login"),[email,setEmail]=useState(""),[pass,setPass]=useState(""),[busy,setBusy]=useState(false);
async function go(){try{setBusy(true);if(mode==="login")await signInWithEmailAndPassword(auth,email.trim(),pass);else await createUserWithEmailAndPassword(auth,email.trim(),pass)}catch(e){Alert.alert("Firebase",e.message)}finally{setBusy(false)}}return <View style={s.center}><Logo/><Text style={s.hero}>Gateway de pagamentos</Text><Text style={s.muted}>Pix, cripto, saques e checkout personalizado.</Text><Input label="E-mail" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><Input label="Senha" value={pass} onChangeText={setPass} secureTextEntry/><Btn title={busy?"Aguarde...":mode==="login"?"Entrar":"Criar conta"} onPress={go}/><Btn title={mode==="login"?"Criar uma conta":"Já tenho conta"} secondary onPress={()=>setMode(mode==="login"?"signup":"login")}/></View>}

function Home({user}){const [tab,setTab]=useState("home"),[result,setResult]=useState(null);
const [amount,setAmount]=useState(""),[name,setName]=useState(""),[doc,setDoc]=useState(""),[desc,setDesc]=useState("");
const [network,setNetwork]=useState("TRC20"),[wallet,setWallet]=useState("");
const [product,setProduct]=useState(""),[media,setMedia]=useState(null);
async function run(path,body){try{setResult(await callApi(path,body))}catch(e){Alert.alert("Gateway",e.message)}}
async function pick(){const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images","videos"],quality:1});if(!r.canceled)setMedia(r.assets[0])}
if(tab==="pix")return <Page title="Cobrar via Pix" back={()=>setTab("home")}><Input label="Valor (R$)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Input label="Nome do pagador" value={name} onChangeText={setName}/><Input label="CPF/CNPJ" value={doc} onChangeText={setDoc}/><Input label="Descrição" value={desc} onChangeText={setDesc}/><Btn title="Criar cobrança Pix" onPress={()=>run("/krypt/pix-create",{amount:Number(amount),payerName:name,payerDocument:doc,description:desc})}/><Result data={result}/></Page>;
if(tab==="crypto")return <Page title="Cobrar Cripto" back={()=>setTab("home")}><Input label="Valor" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Input label="Rede" value={network} onChangeText={setNetwork}/><Input label="Descrição" value={desc} onChangeText={setDesc}/><Btn title="Criar cobrança cripto" onPress={()=>run("/krypt/crypto-create",{amount:Number(amount),network,description:desc})}/><Result data={result}/></Page>;
if(tab==="cashout")return <Page title="Saque" back={()=>setTab("home")}><Input label="Valor" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Input label="Carteira cripto" value={wallet} onChangeText={setWallet}/><Input label="Descrição" value={desc} onChangeText={setDesc}/><Btn title="Solicitar saque" onPress={()=>run("/krypt/cashout",{withdrawalMethod:"CRYPTO",amount:Number(amount),wallet,description:desc})}/><Result data={result}/></Page>;
if(tab==="checkout")return <Page title="Checkout personalizado" back={()=>setTab("home")}><Input label="Produto" value={product} onChangeText={setProduct}/><Input label="Preço" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Input label="Descrição" value={desc} onChangeText={setDesc}/><Btn title="Adicionar imagem/vídeo" secondary onPress={pick}/>{media&&<Text style={s.ok}>Mídia selecionada: {media.fileName||media.uri}</Text>}<Btn title="Criar link de pagamento" onPress={()=>run("/abacate/billing-create",{name:product,price:Number(amount),description:desc,returnUrl:"https://example.com/retorno",completionUrl:"https://example.com/sucesso"})}/><Result data={result}/></Page>;
if(tab==="docs")return <Page title="API & Docs" back={()=>setTab("home")}><Text style={s.cardText}>As chaves dos gateways ficam somente no backend. Nunca coloque KRYPT_CS ou ABACATE_API_KEY no APK.</Text><Btn title="Abrir docs Abacate Pay" onPress={()=>Linking.openURL("https://abacatepay.readme.io/reference/postbillingcreate")}/><Text style={s.cardText}>Proxy esperado: /.netlify/functions/api</Text></Page>;
return <><ScrollView contentContainerStyle={s.wrap}><Logo/><Text style={s.welcome}>Olá, {user.email}</Text><Text style={s.muted}>Escolha uma operação.</Text><View style={s.grid}><Card t="Pix" d="Receber via Pix" onPress={()=>setTab("pix")}/><Card t="Cripto" d="Cobrança crypto" onPress={()=>setTab("crypto")}/><Card t="Saque" d="Retirar saldo" onPress={()=>setTab("cashout")}/><Card t="Checkout" d="Link personalizado" onPress={()=>setTab("checkout")}/><Card t="API" d="Documentação" onPress={()=>setTab("docs")}/></View><Btn title="Sair da conta" secondary onPress={()=>signOut(auth)}/></ScrollView><StatusBar style="light"/></>}
}
function Card({t,d,onPress}){return <Pressable style={s.card} onPress={onPress}><Text style={s.cardTitle}>{t}</Text><Text style={s.muted}>{d}</Text></Pressable>}
function Page({title,back,children}){return <ScrollView contentContainerStyle={s.wrap}><Pressable onPress={back}><Text style={s.back}>‹ Voltar</Text></Pressable><Text style={s.title}>{title}</Text>{children}</ScrollView>}
function Result({data}){return data?<View style={s.result}><Text style={s.resultTitle}>Resposta do gateway</Text><Text style={s.mono}>{JSON.stringify(data,null,2)}</Text></View>:null}

export default function App(){const [user,setUser]=useState(undefined);useEffect(()=>onAuthStateChanged(auth,setUser),[]);if(user===undefined)return <View style={s.center}><Text style={s.muted}>Carregando...</Text></View>;return user?<Home user={user}/>:<Auth/>}

const s=StyleSheet.create({wrap:{padding:22,paddingTop:58,paddingBottom:40,backgroundColor:"#070a10",minHeight:"100%"},center:{flex:1,backgroundColor:"#070a10",padding:24,justifyContent:"center"},logo:{flexDirection:"row",alignItems:"center",gap:12,marginBottom:20},mark:{width:58,height:58,borderRadius:18,backgroundColor:"#071a36",borderWidth:2,borderColor:"#1474ff",alignItems:"center",justifyContent:"center"},markText:{fontSize:34,fontWeight:"900",fontStyle:"italic",color:"#1474ff"},logoName:{fontSize:24,fontWeight:"900",color:"#fff"},logoSub:{fontSize:12,fontWeight:"800",letterSpacing:4,color:"#18dca1"},hero:{fontSize:30,fontWeight:"900",color:"#fff",marginBottom:8},welcome:{fontSize:28,fontWeight:"900",color:"#fff",marginBottom:6},muted:{color:"#8791a5",fontSize:14,lineHeight:21},field:{marginTop:15},label:{color:"#c8d0df",fontSize:13,marginBottom:7},input:{height:52,borderRadius:14,borderWidth:1,borderColor:"#253043",backgroundColor:"#0d121b",color:"#fff",paddingHorizontal:15,fontSize:16},btn:{marginTop:16,height:52,borderRadius:15,backgroundColor:"#18dca1",alignItems:"center",justifyContent:"center"},btn2:{backgroundColor:"#121925",borderWidth:1,borderColor:"#273248"},btnText:{color:"#06100c",fontWeight:"900",fontSize:15},grid:{flexDirection:"row",flexWrap:"wrap",gap:12,marginTop:24,marginBottom:20},card:{width:"47%",minHeight:120,borderRadius:20,borderWidth:1,borderColor:"#202a3a",backgroundColor:"#0d121b",padding:18,justifyContent:"flex-end"},cardTitle:{color:"#fff",fontSize:20,fontWeight:"900",marginBottom:6},cardText:{color:"#c7cfdd",fontSize:15,lineHeight:23,marginTop:18},title:{color:"#fff",fontSize:30,fontWeight:"900",marginTop:12,marginBottom:10},back:{color:"#18dca1",fontWeight:"800",fontSize:16},result:{marginTop:18,padding:15,borderRadius:16,backgroundColor:"#0d121b",borderWidth:1,borderColor:"#253043"},resultTitle:{color:"#fff",fontWeight:"900",marginBottom:8},mono:{color:"#b9c7d9",fontSize:11},ok:{color:"#18dca1",marginTop:12}});
