import React,{useEffect,useRef,useState}from"react";
import{Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{StatusBar}from"expo-status-bar";
import{CameraView,useCameraPermissions}from"expo-camera";
import jpeg from"jpeg-js";

const SAMPLE_SECONDS=20,MIN_BPM=45,MAX_BPM=150;
function classify(b){if(b<50)return{title:"Frequência baixa",note:"Uma leitura isolada não confirma um problema. Se houver sintomas ou persistir, procure avaliação profissional."};if(b>120)return{title:"Frequência alta",note:"Repita em repouso. Se houver dor no peito, falta de ar, desmaio ou mal-estar importante, procure atendimento."};return{title:"Leitura em faixa comum",note:"Isso não comprova que o coração esteja saudável; o app apenas estima a frequência cardíaca."}}
function median(v){const a=[...v].sort((x,y)=>x-y);return a[Math.floor(a.length/2)]}
function estimate(s){if(s.length<8)return null;const x=s.map(a=>a.t),y=s.map(a=>a.v),m=y.reduce((a,b)=>a+b,0)/y.length,c=y.map(a=>a-m);if((x[x.length-1]-x[0])/1000<8)return null;let p=[];for(let i=2;i<c.length-2;i++)if(c[i]>c[i-1]&&c[i]>=c[i+1]&&c[i]>c[i-2]&&c[i]>=c[i+2])p.push(x[i]);let g=[];for(let i=1;i<p.length;i++){let q=(p[i]-p[i-1])/1000;if(q>=.35&&q<=1.5)g.push(q)}if(!g.length)return null;let b=60/median(g);return b>=MIN_BPM&&b<=MAX_BPM?Math.round(b):null}

export default function App(){
 const[permission,requestPermission]=useCameraPermissions(),[running,setRunning]=useState(false),[seconds,setSeconds]=useState(0),[bpm,setBpm]=useState(null),[status,setStatus]=useState("Pronto para medir"),[result,setResult]=useState(null),[history,setHistory]=useState([]),cameraRef=useRef(null),samples=useRef([]),timer=useRef(null),capture=useRef(null);
 useEffect(()=>()=>{clearInterval(timer.current);clearInterval(capture.current)},[]);
 const stop=()=>{clearInterval(timer.current);clearInterval(capture.current);setRunning(false);let e=estimate(samples.current);if(e){setBpm(e);setResult(classify(e));setHistory(h=>[{bpm:e,time:new Date().toLocaleTimeString()},...h].slice(0,10));setStatus("Medição concluída")}else setStatus("Não foi possível obter uma leitura estável. Tente novamente.")};
 const start=()=>{samples.current=[];setBpm(null);setResult(null);setSeconds(0);setRunning(true);setStatus("Coloque a ponta do dedo sobre a câmera traseira e permaneça parado.");timer.current=setInterval(()=>setSeconds(s=>{if(s>=SAMPLE_SECONDS-1){stop();return SAMPLE_SECONDS}return s+1}),1000);capture.current=setInterval(async()=>{try{if(!cameraRef.current)return;let photo=await cameraRef.current.takePictureAsync({quality:.15,skipProcessing:true,base64:true});if(!photo?.base64)return;let raw=jpeg.decode(photo.base64,{useTArray:true}),sum=0,count=0,step=Math.max(4,Math.floor(Math.sqrt(raw.data.length/4)/60));for(let y=0;y<raw.height;y+=step)for(let x=0;x<raw.width;x+=step){let i=(y*raw.width+x)*4;sum+=raw.data[i];count++}if(count)samples.current.push({t:Date.now(),v:sum/count})}catch(e){}},500)};
 if(!permission)return <SafeAreaView style={s.center}><Text style={s.text}>Verificando câmera…</Text></SafeAreaView>;
 if(!permission.granted)return <SafeAreaView style={s.page}><StatusBar style="light"/><View style={s.card}><Text style={s.logo}>♥</Text><Text style={s.title}>Batimento Cardíaco</Text><Text style={s.sub}>Estimativa de frequência cardíaca usando a câmera.</Text><Pressable style={s.button} onPress={requestPermission}><Text style={s.bt}>Permitir câmera</Text></Pressable><Text style={s.disc}>A câmera é usada somente durante a medição. Não é diagnóstico médico.</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.page}><StatusBar style="light"/><ScrollView contentContainerStyle={s.container}><Text style={s.brand}>♥ Batimento</Text><Text style={s.title}>Como está seu ritmo?</Text><Text style={s.sub}>Faça uma medição de 20 segundos em repouso.</Text><View style={s.measure}><View style={s.cam}><CameraView ref={cameraRef} facing="back" style={StyleSheet.absoluteFillObject}/><View style={s.finger}><Text style={s.fingerText}>Coloque o dedo aqui</Text></View></View><Text style={s.timer}>{running?`${seconds}s / 20s`:"20s"}</Text><Text style={s.status}>{status}</Text>{!running?<Pressable style={s.button} onPress={start}><Text style={s.bt}>Iniciar medição</Text></Pressable>:<Pressable style={s.stop} onPress={stop}><Text style={s.bt}>Finalizar</Text></Pressable>}</View>{bpm&&<View style={s.result}><Text style={s.bpm}>{bpm}</Text><Text style={s.unit}>BPM</Text><Text style={s.resultTitle}>{result?.title}</Text><Text style={s.note}>{result?.note}</Text></View>}{history.length>0&&<View style={s.history}><Text style={s.section}>Últimas medições</Text>{history.map((x,i)=><View key={i} style={s.row}><Text style={s.rowBpm}>{x.bpm} BPM</Text><Text style={s.rowTime}>{x.time}</Text></View>)}</View>}<View style={s.warning}><Text style={s.warningTitle}>Importante</Text><Text style={s.warningText}>Este app fornece uma estimativa e não consegue dizer sozinho se o coração está “bem”. Para sintomas fortes, procure atendimento. Emergência no Brasil: 192 (SAMU).</Text></View></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({
 page:{flex:1,backgroundColor:"#07111f"},container:{padding:22,paddingBottom:40},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#07111f"},text:{color:"#fff"},brand:{color:"#ff4d67",fontSize:18,fontWeight:"800",marginBottom:18},title:{color:"#fff",fontSize:30,fontWeight:"900"},sub:{color:"#9fb0c5",fontSize:15,lineHeight:22,marginTop:7,marginBottom:20},card:{margin:20,padding:26,borderRadius:28,backgroundColor:"#101d2d",alignItems:"center"},logo:{fontSize:56,color:"#ff4d67"},measure:{backgroundColor:"#101d2d",borderRadius:28,padding:16,alignItems:"center"},cam:{height:290,width:"100%",borderRadius:22,overflow:"hidden",backgroundColor:"#02060b",position:"relative"},finger:{position:"absolute",left:0,right:0,bottom:25,alignItems:"center"},fingerText:{color:"#fff",backgroundColor:"rgba(0,0,0,.55)",padding:9,borderRadius:12},timer:{fontSize:27,color:"#fff",fontWeight:"900",marginTop:15},status:{color:"#aebed0",textAlign:"center",marginVertical:10,minHeight:40},button:{backgroundColor:"#ff4d67",paddingVertical:15,paddingHorizontal:28,borderRadius:18,width:"100%",alignItems:"center"},stop:{backgroundColor:"#27384b",paddingVertical:15,paddingHorizontal:28,borderRadius:18,width:"100%",alignItems:"center"},bt:{color:"#fff",fontWeight:"800",fontSize:16},result:{marginTop:16,backgroundColor:"#102b25",borderRadius:26,padding:22,alignItems:"center"},bpm:{fontSize:58,fontWeight:"900",color:"#fff"},unit:{color:"#9fb0c5"},resultTitle:{color:"#7ee7bf",fontSize:20,fontWeight:"800",marginTop:10},note:{color:"#c7d4df",textAlign:"center",lineHeight:21,marginTop:8},history:{backgroundColor:"#101d2d",padding:18,borderRadius:22,marginTop:16},section:{color:"#fff",fontSize:18,fontWeight:"800",marginBottom:8},row:{flexDirection:"row",justifyContent:"space-between",paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#203044"},rowBpm:{color:"#fff",fontWeight:"700"},rowTime:{color:"#8193a8"},warning:{marginTop:16,padding:18,borderRadius:20,backgroundColor:"#2a2022"},warningTitle:{color:"#ffb2bb",fontWeight:"900"},warningText:{color:"#d5c7ca",lineHeight:20},disc:{color:"#8798aa",textAlign:"center",fontSize:12,lineHeight:18,marginTop:18}});
